create table parking_slot (
    id              bigint generated by default as identity primary key,
    slot_number     varchar(16)  not null unique,
    floor_no        integer      not null,
    type            varchar(8)   not null,
    status          varchar(12)  not null,
    held_by         varchar(64),
    hold_expires_at timestamp(6) with time zone,
    version         bigint       not null default 0
);

create table parking_session (
    id             bigint generated by default as identity primary key,
    slot_id        bigint        not null references parking_slot (id),
    driver_id      varchar(64)   not null,
    vehicle_number varchar(16)   not null,
    vehicle_type   varchar(8)    not null,
    entry_time     timestamp(6) with time zone not null,
    exit_time      timestamp(6) with time zone,
    rate_per_hour  numeric(10, 2) not null,
    amount         numeric(10, 2),
    status         varchar(8)    not null
);

create index idx_slot_status on parking_slot (status);
create index idx_session_status on parking_session (status);
create index idx_session_slot on parking_session (slot_id);
